kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: komet-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: komet
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
