apiVersion: apps/v1
kind: Deployment
metadata:
  name: komet-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: komet-controller
  template:
    metadata:
      labels:
        name: komet-controller
    spec:
      serviceAccountName: komet-controller
      containers:
        - name: komet-controller
          # Replace this with the built image name
          image: ochorny/komet-controller:0.4.4
          command:
          - komet-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "komet-controller"
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: webhook
                  key: secret
