// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/plerionio/komet-controller/pkg/apis/cloud/v1alpha1.Komet":       schema_pkg_apis_cloud_v1alpha1_Komet(ref),
		"github.com/plerionio/komet-controller/pkg/apis/cloud/v1alpha1.KometSpec":   schema_pkg_apis_cloud_v1alpha1_KometSpec(ref),
		"github.com/plerionio/komet-controller/pkg/apis/cloud/v1alpha1.KometStatus": schema_pkg_apis_cloud_v1alpha1_KometStatus(ref),
	}
}

func schema_pkg_apis_cloud_v1alpha1_Komet(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Komet is the Schema for the komets API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/plerionio/komet-controller/pkg/apis/cloud/v1alpha1.KometSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/plerionio/komet-controller/pkg/apis/cloud/v1alpha1.KometStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/plerionio/komet-controller/pkg/apis/cloud/v1alpha1.KometSpec", "github.com/plerionio/komet-controller/pkg/apis/cloud/v1alpha1.KometStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cloud_v1alpha1_KometSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KometSpec defines the desired state of Komet",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_cloud_v1alpha1_KometStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KometStatus defines the observed state of Komet",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
