apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: knctl-deploy
spec:
  inputs:
    params:
    - name: service
      description: Name of the service to deploy
    - name: namespace
      description: Name of the namespace to deploy
    - name: env
      description: Environment variable
    resources:
    - name: image
      type: image
  steps:
  # the first step is required as knctl doesn't support inCluster configuration.
  - name: kubeconfig
    image: gcr.io/cloud-builders/kubectl # it is huge
    command: ["/bin/bash"]
    args:
    - -c
    - mkdir -p /builder/home/.kube; kubectl config view > /builder/home/.kube/config
  - name: namespace
    image: gcr.io/cloud-builders/kubectl # it is huge
    command: ["/bin/bash"]
    args:
    - -c
    - kubectl create ns ${inputs.params.namespace} --dry-run=true -o yaml | kubectl apply -f -
  - name: rollout
    image: quay.io/openshift-pipeline/knctl
    command: ["/usr/bin/knctl"]
    args:
    - deploy
    - --service
    - ${inputs.params.service}
    - --image
    - ${inputs.resources.image.url}
    - --namespace
    - ${inputs.params.namespace}
    - --env
    - ${inputs.params.env}
